### ISSUE TITLE
what does "You should have keystore in your workspace." mean?

### ISSUE THREAD

**Issue by bullda** [primasio/primas-api-sdk-js#1]
Is that means leaving a file named "keystore"? or something else? 

Thanks for your help. I want to make a test on this sdk.

**Comment by DarrenWonder** [comment]
as a test use, you should put a dir named 'keystore' with [UTC_JSON_Keystore_File](https://theethereum.wiki/w/index.php/Accounts,_Addresses,_Public_And_Private_Keys,_And_Tokens#UTC_JSON_Keystore_File), the example is like below:
![image](https://user-images.githubusercontent.com/12163867/43503538-6b0bbc42-9592-11e8-9809-59d33c1a983d.png)

for more information, you can find in [this page](https://medium.com/@julien.maffre/what-is-an-ethereum-keystore-file-86c8c5917b97)
