### ISSUE TITLE
What does "accountId" mean?

### ISSUE THREAD

**Issue by samma835** [primasio/primas-api-sdk-js#3]
I tried address, integer(like "1178") and username. All failed. Return { result_code: 500, result_msg: 'user not exist' }

So, what does the parameter meaning?

**Comment by LXTyr** [comment]
you should create your account at first, use the [create method](https://github.com/primasio/primas-api-sdk-js/blob/master/README.md#createquery-callback), this method will return a id, that is your accountId, enjoy yourself!

**Comment by bullda** [comment]
Thanks for your response. So, how do I get an existing user's accountId of Primas?

**Comment by koalacxr** [comment]
good question，already added "17.Get address metadata" in the account.md module (https://github.com/primasio/primas-api-doc/blob/master/account.md)

**Comment by bullda** [comment]
Really cool! I'll give it a try. Thanks for your help.

**Comment by bullda** [comment]
btw

**Comment by koalacxr** [comment]
@bullda This interface has just been designed and needs to be developed.

**Comment by koalacxr** [comment]
https://staging.primas.io/main/accounts/800551614ad4e0b656087cc5cbd7e7d6f5dfb81f/metadata

This interface works fine now.

**Comment by bullda** [comment]
Nice, thanks for your hard work! Works like a charm.
